config/routes.rb
Rails.application.routes.draw do
  resources :withdraws_banks


  resources :credit_cards do
    member do
      get :credit_card_image
    end
  end

  

 devise_for :userds ,:path_names => {
	:verify_authy => "/verify-token",
	:enable_authy => "/enable-two-factor",
	:verify_authy_installation => "/verify-installation",

},

controllers: { registrations: "userds/registrations",passwords:"userds/passwords", sessions: "userds/sessions"  ,  invitations: "invitations", two_factor_authentication: "userds/two_factor_authentication",checkga:"userds/checkga",confirmations:"userds/confirmations"  } do
  
  match 'userds/sign_out' => "devise/sessions#destroy"
end



  resources :users_wallets_balances,:except => [:edit,:show,:index]
  resources :users_wallets_balances_frozens,:except => [:index]

  resources :balances_withdraws_statuses do
    member do
      get :withdraw_image
    end
  end
 
  resources :notifications,:except => [:new]
  
  resources :users_groups
  resources :email_templates

  resources :carts,:except => [:edit,:index]
  resources :company_balances
  resources :balances_withdraws
  resources :roles
  resources :cards
  
  resources :watchdogs
  resources :settings


  resources :tickets do
    member do
      get :ticket_image
    end
  end

  
  resources :users_banks
  
   resources :onlinebanks, only: [:show] 


  resources :customsdata
  resources :user_verifications
  resources :transactions
  



   
get 'test_limits' => 'userds#test_limits'

get "come_soon" => "credit_cards#come_soon"

get "getcardtype" => "credit_cards#getcardtype"

get "testniceselect" => "homedevise#testniceselect"
  
get 'userwallet_frozen' => "users_wallets_balances_frozens#userwallet_frozen_get"
  
get 'check_expenses' => "users_wallets_balances_frozens#check_expenses"

get 'payers_welcome' => "userds#payers_welcome"

get 'error_page' => "frontendpages#error_page"

get 'contact' => "frontendpages#contact"


post 'userds/password/forgot', to: 'userds#forgot'

post 'userds/password/reset', to: 'userds#reset'

get "backup_status" => "userds#backup_status"

get "resend_tfa" => "userds#resend_tfa"
post "resend_tfa" => "userds#resend_tfa"
patch "resend_tfa" => "userds#resend_tfa"
get "uniquetel" => "userds#uniquetel"
get "offline_avatar" => "onlinebanks#offline_avatar"
get "exception_ticket" => "onlinebanks#exception_ticket"

get "user_sms_check" => "userds#user_sms_check"
post "user_sms_check" => "userds#user_sms_check_post"

get "balance_with_draw_sms_check" => "balances_withdraws#balance_with_draw_sms_check"
post "balance_with_draw_sms_check" => "balances_withdraws#balance_with_draw_sms_check_post"

  
post "changeprofile" => "userds#changeprofile"
post "edituserprofile" => "user_verifications#edituserprofile"
get "withdraw_status_image" => "balances_withdraws_statuses#withdraw_status_image"


get "mailconfirm" => "user_verifications#mailconfirm" 

get "get_attachment/:id" => "attachments#get_attachment"
get "admin_attach/:id" => "admin_attachments#admin_attach"


get "verify_image" => "user_verifications#verify_image"

get "unlockconfirm" => "user_verifications#unlockconfirm"

get "verify_image" => "user_verifications#verify_image"
post "balances_withdraws/:id" => "balances_withdraws#update_hint"
  
get"searchpost" => "transactions#search"
post"searchpost" => "transactions#searchpost"

get "types" => "currencies_withdraw_ratios#types"
post "types" => "currencies_withdraw_ratios#types"
patch "types" => "currencies_withdraw_ratios#types"

get "currencies" => "currencies_withdraw_types#currencies"
post "currencies" => "currencies_withdraw_types#currencies"
patch "currencies" => "currencies_withdraw_types#currencies"


get "buycart" => "carts#buycart"
get "payment_method" => "carts#payment_method"

get "payment_method_ratios" => "carts#payment_method_ratios"


get "get_expenses" => "balances_withdraws#get_expenses"
get "get_previous" => "balances_withdraws#get_previous"

get "review_balance_withdraw" => "balances_withdraws#review_balance_withdraw"
post "review_balance_withdraw" => "balances_withdraws#review_balance_withdraw"

post "review_western_gram" => "balances_withdraws#review_western_gram"
get "review_western_gram" => "balances_withdraws#review_western_gram_get"
post "review_egyptian_mail" => "balances_withdraws#review_egyptian_mail"

get "sendsms" => "user_verifications#sendsms"
post "sendsms" => "user_verifications#sendsms_post"

get "sendvoicesms" => "user_verifications#sendvoicesms"
post "sendvoicesms" => "user_verifications#sendvoicesms_post"



get "help_center" => "tickets#help_center"

get "freshdesk" => "tickets#freshdesk"
post "freshdesk" => "tickets#freshdesk_post"

get "send2fasms" => "user_verifications#send2fasms"

get "resendsms" => "user_verifications#resendsms"
get "verifysms" => "user_verifications#verifysms"
get "veriffysms" => "user_verifications#veriffysms" 
get "resendsmsa2" => "user_verifications#resendsmsa2"

post "changetel" => "user_verifications#changetel"

get "user_wallets_transactions" => "transactions#user_wallets_transactions"

get "pre_verification" => "user_verifications#pre_verification"
get "all_verifications" => "user_verifications#all_verifications"

get "visa_activate" => "user_verifications#visa_activate"
get "address_activate" => "user_verifications#address_activate"
get "selfie_activate" => "user_verifications#selfie_activate"

get "exceptionmessage" => "balances_withdraws#exceptionmessage"
post "exceptionmessage" => "balances_withdraws#exceptionmessage"
patch "exceptionmessage" => "balances_withdraws#exceptionmessage"

get "balances_withdraws_methods" => "balances_withdraws#methods"
post "balances_withdraws_methods" => "balances_withdraws#methods"
patch "balances_withdraws_methods" => "balances_withdraws#methods"

post "searchpostbank" => "users_banks#searchpost"

get "users_banks_methods" => "users_banks#methods"
post "users_banks_methods" => "users_banks#methods"
patch "users_banks_methods" => "users_banks#methods"

get "users_banks_types" => "users_banks#types"
post "users_banks_types" => "users_banks#types"
patch "users_banks_types" => "users_banks#types"

get "users_banks_currencies" => "users_banks#currencies"
post "users_banks_currencies" => "users_banks#currencies"
patch "users_banks_currencies" => "users_banks#currencies"

post "add_bank_confirm" => "users_banks#add_bank_confirm"

get "review_egyptian_mail_post" => "users_banks#review_egyptian_mail"
post "review_egyptian_mail_post" => "users_banks#review_egyptian_mail_post"

get "review_new_bank" => "users_banks#new_review"

post "review_new_bank" => "users_banks#new_review_post"
patch "review_new_bank" => "users_banks#new_review_post"

get "users_banks_egyptian_mail" => "users_banks#egyptian_mail"
get "edit_egyptian_mail_bank" => "users_banks#edit_egyptian_mail_bank"
post "edit_egyptian_mail_bank" => "users_banks#edit_egyptian_mail_bank"
get "users_banks_western_gram" => "users_banks#western_gram"

get "users_banks/:id/edit_egyptian_mail" => "users_banks#edit_egyptian_mail", as: "edit_egyptian_mail"

get "users_banks/:id/edit_western_gram" => "users_banks#edit_western_gram", as: "edit_western_gram"
get "users_banks/:id/edit_bank" => "users_banks#edit_bank", as: "edit_bank"

post  'users_banks_save_western_gram' => 'users_banks#save_western_gram'
post "edit_western" => "users_banks#post_edit_western"
patch "edit_western" => "users_banks#post_edit_western"

post "users_banks_save_bank" => "users_banks#post_edit_western"

post "edit_egyptian_mail" => "users_banks#post_edit_egyptianmail"
patch "edit_egyptian_mail" => "users_banks#post_edit_egyptianmail"

post  'users_banks_save_egyptian_mail' => 'users_banks#save_egyptian_mail'

post  'users_bankssave' => 'users_banks#save'
get  'users_bankssave' => 'users_banks#getsave'

###########################################

post "id_activate" => "user_verifications#update"
patch "id_activate" => "user_verifications#update"

get 'homepages/home'

root 'userds#account_settings' 
get "welcome" => "welcome#welcome"
   
get "account_settings" => "userds#account_settings"
get "user_profile" => "userds#user_profile"
get "log_operations" => "userds#log_operations"
get "fail_signin" => "userds#fail_signin"
get "failed_operations" => "userds#failed_operations"
get "userstatistics" => "userds#userstatistics"
get "allusers" => "userds#index"

put "account_settings" => "userds#set_account_info"

get "useractive" => "userds#uactive"

get "change_locale" => "userds#change_locale"

get "sms_deactivate" => "user_verifications#sms_deactivate"
get "sms_activate" => "user_verifications#sms_activate"

post "sms_activate" => "user_verifications#sms_activate_post"

post "email_activate_post" => "user_verifications#email_activate_post"

get "active_otp_secret" => "user_verifications#active_otp_secret"

get "previousattachments" => "user_verifications#previous_attachments"

get "closeticket" => "tickets#closeticket"

get "listticket" => "tickets#index"

get "ticketreply" => "tickets#replay"
post "ticketreply" => "tickets#create"

get "ubankaccount" => "users_banks#useraccounts"

get "users_banks_main" => "users_banks#main_bank"

post "users_banks_main" => "users_banks#main_bank_post"

get "balances_withdraws_main" => "balances_withdraws#main"

get "egyptian_mail" => "balances_withdraws#egyptian_mail"

get "edit_bank_conversion" => "users_banks#edit_bank_conversion"

get "western_gram" => "balances_withdraws#western_gram"

post  'save_western_gram' => 'balances_withdraws#save_western_gram'

post  'save_egyptian_mail' => 'balances_withdraws#save_egyptian_mail'

get 'operations_details' => 'users_wallets_balances#operations_details'

post  'balancewithdrawsave' => 'balances_withdraws#save'
get 'userbankdids' => 'users_banks#for_balanceop'
get 'userwallets' => 'users_wallets_balances#walletselection'
get 'walletfrozen' => 'users_wallets_balances_frozens#walletfrozen'

get 'mailstatus' => 'users_wallets_balances_frozens#mailstatus'
get 'namestatus' => 'users_wallets_balances_frozens#namestatus'

app/helpers/balances_withdraws_helper.rb
module BalancesWithdrawsHelper
end

app/views/balances_withdraws/_form.html.erb
<script>
$(document).ready(function(){
	$('#balances_withdraw_user_id').change(function(){
		var buid = $('#balances_withdraw_user_id').val();
		if(buid != 0)
		{
			$.ajax({
				type:'get',
				url:'/userbankdids',
				data:{id:buid},
                                contentType: "application/json",              
                                dataType: "json",
				cache:false,
				success: function(data){
                                      {
                                         $("#user_bank_select").empty();

				            $.each(data, function () {
				                $("#user_bank_select").append($("<option></option>").val(this['id']).html(this['account_name']));
				            });
					}

 				}
			});
		}
	})
 

})
</script>



<%= form_for(@balances_withdraw) do |f| %>
  <% if @balances_withdraw.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@balances_withdraw.errors.count, "error") %> prohibited this balances_withdraw from being saved:</h2>

      <ul>
      <% @balances_withdraw.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user.role_id == 1 %>
    <div class="field">
       <%= f.label :user_id , t('User') %><br>
        <%= f.select :user_id, Userd.all.collect {|p| [ "#{p.username} / #{p.email}", p.id ] },{ :prompt => t('Select a User')}, {  :class => 'form-control' } %>
        

   </div>
 <% else %>
     <%= f.hidden_field :user_id, :value=>  current_userd.id   %>
 <% end %>
 <%= link_to t('New User bank Account'), new_users_bank_path %>

  <div class="field">

    <%= f.label :user_bank_id , t('User bank account') %><br />       

        <%= f.select :user_bank_id, UsersBank.where(user_id: current_user.id).collect {|p| [ "#{p.account_name} / #{p.account_number}", p.bank_id ] },{ :prompt => t('Select a bank')}, {  :class => 'form-control' } %>


  </div>

  <div class="field">
    <%= f.label :thesum , t('the sum') %><br>
    <%= f.text_field :thesum ,  :class => 'form-control', :required => true %>
  </div>


 
   
  
  <div class="field">
    <%= f.label :hint, t('Hint') %><br>
    <%= f.text_area :hint , :class => 'form-control'  %>
  </div>
<% if current_userd.role_id == 1  %>

  <div class="field">
    <%= f.label :expect_date, t('Expect date') %><br>
    <%= f.date_select :expect_date ,start_year: 2016 ,end_year: 2050 , use_month_numbers: true, prompt: { day: t('Select day'), month: t('Select month'), year: t('Select year') },  :class => 'form-control' %>

  </div>
<% end %>

 
    <div class="actions  text-center"> 
 
<button type="submit" class="btn btn-primary waves-effect waves-light m-t-15 text-center"><%= t('Search') %> </button>

  </div>
<% end %>

app/views/balances_withdraws/balance_with_draw_sms_check.html.erb
<!doctype html>
<html dir='ltr' lang="en">

<head>

    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- SEO -->
    <title><%= flash[:notice] %></title>
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <!-- Google Authorship and Publisher Markup -->
    <link rel="author" href="" />
    <link rel="publisher" href="" />
    <!-- Schema.org markup for Google+ -->
    <meta itemprop="name" content="" />
    <meta itemprop="description" content="" />
    <meta itemprop="image" content="<%= format_link(request) %>/assets
/imgs/content-covre.png" />
    <!-- Twitter Card data -->
    <meta name="twitter:card" content="<%= format_link(request) %>/assets
/imgs/content-covre.png" />
    <meta name="twitter:site" content="" />
    <meta name="twitter:title" content="" />
    <meta name="twitter:description" content="" />
    <meta name="twitter:creator" content="" />
    <meta name="twitter:image:src" content="<%= format_link(request) %>/assets
/imgs/content-covre.png" />
    <!-- Open Graph data -->
    <meta property="og:title" content="" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="http://payers.net/" />
    <meta property="og:image" content="<%= format_link(request) %>/assets
/imgs/content-covre.png" />
    <meta property="og:description" content="" />
    <meta property="og:site_name" content="" />
    <meta property="fb:admins" content="" />
    <!-- Schema -->
    <script type="application/ld+json">
    { "@context": "http://schema.org", "@type": "webSite", "url": "http://www.crtivo.studio", "name": "12 Cups Website", "description": "for selling coffee " }
    </script>
    <!-- other SEO info -->
    <meta name="revisit-after" content="5 days">
    <meta name="robots" content="index,follow" />
    <meta name="rating" content="general" />
    <meta name="author" content="" />
    <meta name="copyrights" content="" />
    <meta name="alexaVerifyID" content="" />
    <link rel="alternate" type="application/rss+xml" title="RSS 2.0" href="rsslink" />
    <!-- FavsIcons -->
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <link rel="apple-touch-icon" href="/icon.png" />
    <link rel="apple-touch-startup-image" href="/home.png" />
    <!-- Head Inc -->
    <!-- <script data-pace-options='{ "ajax": false, "elements": false, "restartOnRequestAfter": false, "restartOnPushState":false }' src="resources/js/pace.js"></script> -->
    <link rel="stylesheet" href="/assets/css/layout.css" />
    <link rel="stylesheet" href="/assets/css/rtl.css" />
    <!-- <script src='https://maps.googleapis.com/maps/api/js?v=3.exp'></script> -->
    <!-- Google Analytices Code -->
    <script>
    </script>
</head>
<!-- || head area end || -->
<!-- || page body start || -->

<body id="login-page">
    <div class="bannerpage bg-white min-f-height-vh pos-relative">
        <div class="logo-postion pos-absolute">
            <div class="logo-section">
                <a href="/" class="b-boxshadow">
                <img src="<%= format_link(request) %>/assets
/imgs/white-logo.png" alt="white-logo" class="f-width">
            </a>
            </div>
        </div>
        <div class="bannersection pos-absolute f-height">
            <figure>
                <img src="<%= format_link(request) %>/assets
/imgs/loginhero2.png" alt="loginhero2" class="imagecover pos-absolute">
            </figure>
            <% flash.each do |name, msg| %>
            <div class="pos-absolute f-width padding-hor-lg bannersection-caption clearfix">
            <div class="msg-alert alert box-size border-color-brand hlf-btm bg-white padding-ver-xs pull-left clearfix">
                <span class="ico icon ic-right text-green"></span>
                <h5 class="sm-lg-fontsize text-dgray font-bold"><%= content_tag :div, msg, :id => "flash_#{name}" %></h5>
                <p class="sm-md-fontsize text-mgray"><%= notice %></p>

                <span class="alert-close icon-Plus-white"><%= alert %></span>
            </div>
        </div>
         <% end %>

         <%= yield %>

         
        </div>
        <div class="formsection padding-hor-md box-size">


        
          
          
            <div class="formwrap pad-left-sm f-width pad-right-sm hlf-e-btm">
               
            <%= form_for :sms_verify, url: balance_with_draw_sms_check_path do |form| %>
                
                    <div class="self-label">
                        <label>

                            <%= form.text_field :code, :class => 'selfinput',:id => 'code'  %>
                            
                           
                            
                            <span class="placeholder-span">رمز التاكيد</span>
                          </label>
                      </div>

                      <%# link_to "Sign out", send("destroy_#{resource_name}_session_path"), :method => :get %>
                <div id="resendcode" style="display: none;">
                <% if current_userd.sms_active == 1 %>
                <a href="/resendsms" class="mrg-top-sm db-block sm-md-fontsize font-bold text-dgray text-hover-blue">إعادة الإرسال <i class="icon ic-icons-523"></i> </a>
                <% else %>
                <a href="/resendsms" class="mrg-top-sm db-block sm-md-fontsize font-bold text-dgray text-hover-blue">إعادة الإرسال <i class="icon ic-icons-523"></i> </a>
                <% end %>
                </div>
               <div id="timer"></div>
                <div class="row row-default l-height-md padding-ver-md">
                    <div class="col-xs-12">
                        <div class="text-left">
                            <input type="submit" name="submit" value="تاكيد" class="btn-shadow radius-md btn text-white text-hover-white bg-black hover-bg-brand md-padding">
                            
                            </div>
                        </div>
                    </div>
                    <% end %>
                </div>
            
           
        <%# render :partial => 'layouts/upanelheader' %>



          <!-- ============================================================== -->
                   <!-- Start right Content here -->
                   <!-- ============================================================== -->


                         
                           <%# render :partial => 'layouts/upanelside' %>

        <%# render :partial => 'layouts/upanelfooter' %>


      
            

            
            <footer class="formfooter padding-hor-lg hlf-btm sr-only-sm-xs">
                 <p class="footer-copyright sm-sm-fontsize font-bold text-blue pull-left">
                        <%= t('All Rights Reserved Owned by Payers')%> @ <%= Time.current.year%>
                    </p>
            <ul class="footer-ul sm-sm-fontsize font-bold">
			<li><a href="https://support.payers.net/support/solutions" target="_blank"><%= t('How To Use') %></a></li>
			<li><a href="https://www.payers.net/privacy.html" target="_blank"><%= t('Privacy Policy') %></a></li>
			<li><a href="https://www.payers.net/money-laundry.html" target="_blank"><%= t('Money Landury') %></a></li>
		    </ul>

            </footer>
        </div>
    </div>
    <!-- || footer scripts start || -->
    <script src="/assets/js/jquery.js"></script>
    <script src="/assets/js/app.js"></script>
    <script src="/assets/js/slick.min.js"></script>
    <!-- || footer scripts ends || -->
</body>
<!-- || page body ends || -->

</html>
<!-- <script>
	setTimeout(function() {
    $('#resendcode').show();
}, 60000);
</script>
 -->
 <script>
// var timer2 = "0:59";
// var interval = setInterval(function() {


//   var timer = timer2.split(':');
//   //by parsing integer, I avoid all extra string processing
//   var minutes = parseInt(timer[0], 10);
//   var seconds = parseInt(timer[1], 10);
//   --seconds;
//   minutes = (seconds < 0) ? --minutes : minutes;
//   if (minutes < 0) {
//     clearInterval(interval);
// $('#resendcode').show();
// $('#countdown').hide()}
//   // seconds = (seconds < 0) ? 59 : seconds;
//   // seconds = (seconds < 10) ? '0' + seconds : seconds;
//   //minutes = (minutes < 10) ?  minutes : minutes;
//   $('#countdown').html('<%# t("Resend code link will appear after") %>'+ " " + minutes + ':' + seconds);
//   timer2 = minutes + ':' + seconds;
// }, 1000);
var timer = 120;

var interval = setInterval(function() {
    timer--;
    $('#timer').text('<%= t("Resend code link will appear after") %>'+ ' '+ timer);
    if (timer === 0) {
    	clearInterval(interval);
        $('#resendcode').show();
        $('#timer').hide()}
}, 1000);
</script>

app/views/balances_withdraws/canceloperation.html.erb
Done
<%=debug (@balancewithdraw.status) %>

app/views/balances_withdraws/changstatuspost.html.erb
<%=debug(params)%>

app/views/balances_withdraws/disapprovewithdraw.html.erb
<%# debug   @params %> <br />

<%= form_for :balancediswithdraw do |f| %>
   <%= f.hidden_field :id ,:value => params[:id] %>
   <%= t('reason') %> : <%= f.text_area :hint  %>
 
   <div class="actions  text-center"> 
 
<button type="submit" class="btn btn-primary waves-effect waves-light m-t-15 text-center"><%= t('Save') %> </button>

  </div>


<% end %>

app/views/balances_withdraws/edit.html.erb
<h1><%= t('Editing Balances Withdraw') %></h1>

<%# render 'form' %>


<%= form_for(@balances_withdraw) do |f| %>
  <% if @balances_withdraw.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@balances_withdraw.errors.count, "error") %> prohibited this balances_withdraw from being saved:</h2>

      <ul>
      <% @balances_withdraw.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 

  <div class="field">
    <%= f.label :thesum ,t('the sum') %><br>
    <%=  @balances_withdraw.thesum   %>
  </div>


 
   
  <div class="field">
    <%= f.label :status,t('Status')  %><br>
    <%# f.text_field :status %>
<% if  userprivilage.withdrawapprove == true or current_userd.role_id == 1  %>
       <%= f.select :status, options_for_select( [["جديد","new"],["تم استلامه","receipt"],["جاري العمل عليه","hold"],["في الانتظار","wait"],["رفض الطلب","refused"]])  ,{}, {  :class => 'form-control' } %>
 
<% end %>
  </div>
 
<% if  userprivilage.withdrawapprove == true or current_userd.role_id == 1  %>

  <div class="field">
    <%= f.label :expect_date,t('Expect date')  %><br>
    <%= f.date_select :expect_date  ,start_year: 2016 ,end_year: 2050 , use_month_numbers: true, prompt: { day: t('Select day'), month: t('Select month'), year: t('Select year') },  :class => 'form-control' %>

  </div>
<% end %>

 
   <div class="actions  text-center"> 
 
<button type="submit" class="btn btn-primary waves-effect waves-light m-t-15 text-center"><%= t('Save') %> </button>

  </div>

<% end %>

<%# link_to '<button type="button" class="btn btn-primary waves-effect waves-light "><i class="fa fa-eye"></i></button>'.html_safe, @balances_withdraw %>  
<%# link_to t('Back'), balances_withdraws_path %>

<%= link_to "<button type='button' class='btn btn-wide btn-primary'><span class='btn-label'><i class='fa fa-angle-right'></i> </span>#{t('Back')}</button>".html_safe, balances_withdraws_path , { :class=>'linktop' } %>

app/views/balances_withdraws/save.html.erb




<%= debug (@oldbalance) %>

<%= debug (@newbalance) %>


<%= debug (@balances_withdraw.thesum) %>

<%= debug(@expenses) %>

<%= debug (@balances_withdraw.netsum) %>


<%= debug(@wallet.id) %>

<%= debug(@balances_withdraw.wallet_id) %>








app/views/balances_withdraws/save_western_gram.html.erb
<%= params['users_country']['country'] %>
<%= debug (params) %>