config/routes.rb
Rails.application.routes.draw do
  resources :withdraws_banks


  resources :credit_cards do
    member do
      get :credit_card_image
    end
  end

  

 devise_for :userds ,:path_names => {
	:verify_authy => "/verify-token",
	:enable_authy => "/enable-two-factor",
	:verify_authy_installation => "/verify-installation",

},

controllers: { registrations: "userds/registrations",passwords:"userds/passwords", sessions: "userds/sessions"  ,  invitations: "invitations", two_factor_authentication: "userds/two_factor_authentication",checkga:"userds/checkga",confirmations:"userds/confirmations"  } do
  
  match 'userds/sign_out' => "devise/sessions#destroy"
end



  resources :users_wallets_balances,:except => [:edit,:show,:index]
  resources :users_wallets_balances_frozens,:except => [:index]

  resources :balances_withdraws_statuses do
    member do
      get :withdraw_image
    end
  end
 
  resources :notifications,:except => [:new]
  
  resources :users_groups
  resources :email_templates

  resources :carts,:except => [:edit,:index]
  resources :company_balances
  resources :balances_withdraws
  resources :roles
  resources :cards
  
  resources :watchdogs
  resources :settings


  resources :tickets do
    member do
      get :ticket_image
    end
  end

  
  resources :users_banks
  
   resources :onlinebanks, only: [:show] 


  resources :customsdata
  resources :user_verifications
  resources :transactions
  



   
get 'test_limits' => 'userds#test_limits'

get "come_soon" => "credit_cards#come_soon"

get "getcardtype" => "credit_cards#getcardtype"

get "testniceselect" => "homedevise#testniceselect"
  
get 'userwallet_frozen' => "users_wallets_balances_frozens#userwallet_frozen_get"
  
get 'check_expenses' => "users_wallets_balances_frozens#check_expenses"

get 'payers_welcome' => "userds#payers_welcome"

get 'error_page' => "frontendpages#error_page"

get 'contact' => "frontendpages#contact"


post 'userds/password/forgot', to: 'userds#forgot'

post 'userds/password/reset', to: 'userds#reset'

get "backup_status" => "userds#backup_status"

get "resend_tfa" => "userds#resend_tfa"
post "resend_tfa" => "userds#resend_tfa"
patch "resend_tfa" => "userds#resend_tfa"
get "uniquetel" => "userds#uniquetel"
get "offline_avatar" => "onlinebanks#offline_avatar"
get "exception_ticket" => "onlinebanks#exception_ticket"

get "user_sms_check" => "userds#user_sms_check"
post "user_sms_check" => "userds#user_sms_check_post"

get "balance_with_draw_sms_check" => "balances_withdraws#balance_with_draw_sms_check"
post "balance_with_draw_sms_check" => "balances_withdraws#balance_with_draw_sms_check_post"

  
post "changeprofile" => "userds#changeprofile"
post "edituserprofile" => "user_verifications#edituserprofile"
get "withdraw_status_image" => "balances_withdraws_statuses#withdraw_status_image"


get "mailconfirm" => "user_verifications#mailconfirm" 

get "get_attachment/:id" => "attachments#get_attachment"
get "admin_attach/:id" => "admin_attachments#admin_attach"


get "verify_image" => "user_verifications#verify_image"

get "unlockconfirm" => "user_verifications#unlockconfirm"

get "verify_image" => "user_verifications#verify_image"
post "balances_withdraws/:id" => "balances_withdraws#update_hint"
  
get"searchpost" => "transactions#search"
post"searchpost" => "transactions#searchpost"

get "types" => "currencies_withdraw_ratios#types"
post "types" => "currencies_withdraw_ratios#types"
patch "types" => "currencies_withdraw_ratios#types"

get "currencies" => "currencies_withdraw_types#currencies"
post "currencies" => "currencies_withdraw_types#currencies"
patch "currencies" => "currencies_withdraw_types#currencies"


get "buycart" => "carts#buycart"
get "payment_method" => "carts#payment_method"

get "payment_method_ratios" => "carts#payment_method_ratios"


get "get_expenses" => "balances_withdraws#get_expenses"
get "get_previous" => "balances_withdraws#get_previous"

get "review_balance_withdraw" => "balances_withdraws#review_balance_withdraw"
post "review_balance_withdraw" => "balances_withdraws#review_balance_withdraw"

post "review_western_gram" => "balances_withdraws#review_western_gram"
get "review_western_gram" => "balances_withdraws#review_western_gram_get"
post "review_egyptian_mail" => "balances_withdraws#review_egyptian_mail"

get "sendsms" => "user_verifications#sendsms"
post "sendsms" => "user_verifications#sendsms_post"

get "sendvoicesms" => "user_verifications#sendvoicesms"
post "sendvoicesms" => "user_verifications#sendvoicesms_post"



get "help_center" => "tickets#help_center"

get "freshdesk" => "tickets#freshdesk"
post "freshdesk" => "tickets#freshdesk_post"

get "send2fasms" => "user_verifications#send2fasms"

get "resendsms" => "user_verifications#resendsms"
get "verifysms" => "user_verifications#verifysms"
get "veriffysms" => "user_verifications#veriffysms" 
get "resendsmsa2" => "user_verifications#resendsmsa2"

post "changetel" => "user_verifications#changetel"

get "user_wallets_transactions" => "transactions#user_wallets_transactions"

get "pre_verification" => "user_verifications#pre_verification"
get "all_verifications" => "user_verifications#all_verifications"

get "visa_activate" => "user_verifications#visa_activate"
get "address_activate" => "user_verifications#address_activate"
get "selfie_activate" => "user_verifications#selfie_activate"

get "exceptionmessage" => "balances_withdraws#exceptionmessage"
post "exceptionmessage" => "balances_withdraws#exceptionmessage"
patch "exceptionmessage" => "balances_withdraws#exceptionmessage"

get "balances_withdraws_methods" => "balances_withdraws#methods"
post "balances_withdraws_methods" => "balances_withdraws#methods"
patch "balances_withdraws_methods" => "balances_withdraws#methods"

post "searchpostbank" => "users_banks#searchpost"

get "users_banks_methods" => "users_banks#methods"
post "users_banks_methods" => "users_banks#methods"
patch "users_banks_methods" => "users_banks#methods"

get "users_banks_types" => "users_banks#types"
post "users_banks_types" => "users_banks#types"
patch "users_banks_types" => "users_banks#types"

get "users_banks_currencies" => "users_banks#currencies"
post "users_banks_currencies" => "users_banks#currencies"
patch "users_banks_currencies" => "users_banks#currencies"

post "add_bank_confirm" => "users_banks#add_bank_confirm"

get "review_egyptian_mail_post" => "users_banks#review_egyptian_mail"
post "review_egyptian_mail_post" => "users_banks#review_egyptian_mail_post"

get "review_new_bank" => "users_banks#new_review"

post "review_new_bank" => "users_banks#new_review_post"
patch "review_new_bank" => "users_banks#new_review_post"

get "users_banks_egyptian_mail" => "users_banks#egyptian_mail"
get "edit_egyptian_mail_bank" => "users_banks#edit_egyptian_mail_bank"
post "edit_egyptian_mail_bank" => "users_banks#edit_egyptian_mail_bank"
get "users_banks_western_gram" => "users_banks#western_gram"

get "users_banks/:id/edit_egyptian_mail" => "users_banks#edit_egyptian_mail", as: "edit_egyptian_mail"

get "users_banks/:id/edit_western_gram" => "users_banks#edit_western_gram", as: "edit_western_gram"
get "users_banks/:id/edit_bank" => "users_banks#edit_bank", as: "edit_bank"

post  'users_banks_save_western_gram' => 'users_banks#save_western_gram'
post "edit_western" => "users_banks#post_edit_western"
patch "edit_western" => "users_banks#post_edit_western"

post "users_banks_save_bank" => "users_banks#post_edit_western"

post "edit_egyptian_mail" => "users_banks#post_edit_egyptianmail"
patch "edit_egyptian_mail" => "users_banks#post_edit_egyptianmail"

post  'users_banks_save_egyptian_mail' => 'users_banks#save_egyptian_mail'

post  'users_bankssave' => 'users_banks#save'
get  'users_bankssave' => 'users_banks#getsave'

###########################################

post "id_activate" => "user_verifications#update"
patch "id_activate" => "user_verifications#update"

get 'homepages/home'

root 'userds#account_settings' 
get "welcome" => "welcome#welcome"
   
get "account_settings" => "userds#account_settings"
get "user_profile" => "userds#user_profile"
get "log_operations" => "userds#log_operations"
get "fail_signin" => "userds#fail_signin"
get "failed_operations" => "userds#failed_operations"
get "userstatistics" => "userds#userstatistics"
get "allusers" => "userds#index"

put "account_settings" => "userds#set_account_info"

get "useractive" => "userds#uactive"

get "change_locale" => "userds#change_locale"

get "sms_deactivate" => "user_verifications#sms_deactivate"
get "sms_activate" => "user_verifications#sms_activate"

post "sms_activate" => "user_verifications#sms_activate_post"

post "email_activate_post" => "user_verifications#email_activate_post"

get "active_otp_secret" => "user_verifications#active_otp_secret"

get "previousattachments" => "user_verifications#previous_attachments"

get "closeticket" => "tickets#closeticket"

get "listticket" => "tickets#index"

get "ticketreply" => "tickets#replay"
post "ticketreply" => "tickets#create"

get "ubankaccount" => "users_banks#useraccounts"

get "users_banks_main" => "users_banks#main_bank"

post "users_banks_main" => "users_banks#main_bank_post"

get "balances_withdraws_main" => "balances_withdraws#main"

get "egyptian_mail" => "balances_withdraws#egyptian_mail"

get "edit_bank_conversion" => "users_banks#edit_bank_conversion"

get "western_gram" => "balances_withdraws#western_gram"

post  'save_western_gram' => 'balances_withdraws#save_western_gram'

post  'save_egyptian_mail' => 'balances_withdraws#save_egyptian_mail'

get 'operations_details' => 'users_wallets_balances#operations_details'

post  'balancewithdrawsave' => 'balances_withdraws#save'
get 'userbankdids' => 'users_banks#for_balanceop'
get 'userwallets' => 'users_wallets_balances#walletselection'
get 'walletfrozen' => 'users_wallets_balances_frozens#walletfrozen'

get 'mailstatus' => 'users_wallets_balances_frozens#mailstatus'
get 'namestatus' => 'users_wallets_balances_frozens#namestatus'

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  before_action :set_credit_card, only: [:show, :edit, :update, :destroy]
  before_filter :set_come_soon,:except =>[:come_soon]



  def set_come_soon
       redirect_to come_soon_path

  end

  def come_soon

    render layout: false


  end
  # GET /credit_cards
  def index

    begin
    #appear only approved or pending cards
    @credit_cards = CreditCard.where(:status => [ 2,1 ],:user_id => current_userd.id ).all.order('created_at DESC')
    rescue => e
      @code = SecureRandom.hex

      @log =  ErrorsLog.create(:userd_id => current_userd.id,:error_msg => e.message.to_s,:error_code => @code.to_s) 
      redirect_to controller: 'frontendpages', action: 'error_page', id: @log.id
    end

  end

  # GET /credit_cards/1
  def show

    begin
    rescue => e
      @code = SecureRandom.hex

      @log =  ErrorsLog.create(:userd_id => current_userd.id,:error_msg => e.message.to_s,:error_code => @code.to_s) 
      redirect_to controller: 'frontendpages', action: 'error_page', id: @log.id
    end

  end

  #get type of card
  def getcardtype

    begin
    @number = params[:number].to_i
    @detector = CreditCardValidations::Detector.new(@number)
    @brand =   @detector.brand
    
    if  @detector.brand == nil
      @brand =  t("invalid")
    end
    render :json => { 'type': @brand }

    rescue => e
      @code = SecureRandom.hex

      @log =  ErrorsLog.create(:userd_id => current_userd.id,:error_msg => e.message.to_s,:error_code => @code.to_s) 
      redirect_to controller: 'frontendpages', action: 'error_page', id: @log.id
    end

  end

  # GET /credit_cards/new
  def new

    begin
    @credit_card = CreditCard.new

    rescue => e
      @code = SecureRandom.hex

      @log =  ErrorsLog.create(:userd_id => current_userd.id,:error_msg => e.message.to_s,:error_code => @code.to_s) 
      redirect_to controller: 'frontendpages', action: 'error_page', id: @log.id
    end

  end

  # GET /credit_cards/1/edit
  def edit

    begin
    rescue => e
      @code = SecureRandom.hex

      @log =  ErrorsLog.create(:userd_id => current_userd.id,:error_msg => e.message.to_s,:error_code => @code.to_s) 
      redirect_to controller: 'frontendpages', action: 'error_page', id: @log.id
    end

  end

  # POST /credit_cards
  def create

    begin
    @credit_card = CreditCard.new(credit_card_params)
    @credit_card.user_id = current_userd.id

    respond_to do |format|
      if @credit_card.save

        if @credit_card.status == 2
          @status = "Pending"

        elsif @credit_card.status == 1
          @status = "Approved"

        elsif @credit_card.status == 0
          @status = "Not Approved"
        end

        Watchdog.create(:user_id => current_userd.id,:added_by => current_userd.id,:controller => 'credit_cards', :action_page =>"create_credit_card",:foreign_id=>@credit_card.id ,:details=> "Credit Card has been added by/"+ current_userd.username + " /with status/ " + @status + " /with number/ " + @credit_card.card_no )
        format.html { redirect_to credit_cards_path, notice: t('Credit card was successfully created') }
        format.json { render :show, status: :created, location: @credit_card }
      
      else
        Watchdog.create(:user_id => current_userd.id,:added_by => current_userd.id,:controller => 'credit_cards', :action_page =>"create_credit_card",:foreign_id=>@credit_card.id ,:details=> "Credit Card can't be added by/"+ current_userd.username )
        format.html { render :new }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      
      end
    end

    rescue => e
      @code = SecureRandom.hex

      @log =  ErrorsLog.create(:userd_id => current_userd.id,:error_msg => e.message.to_s,:error_code => @code.to_s) 
      redirect_to controller: 'frontendpages', action: 'error_page', id: @log.id
    end

  end

  def credit_card_image

    @credit_card = CreditCard.where(:id => params[:id].to_i).first
    if  current_userd &&    @credit_card.userd_id == current_userd.id

     send_file CreditCard.where(:id => params[:id].to_i,:userd_id => current_userd.id ).first.photo.path

    else 

     redirect_to(credit_cards_path,:notice => t('A picture you are not allowed to access'))
     end



  end

  # PATCH/PUT /credit_cards/1
  def update

    begin
    respond_to do |format|
      @credit_card.user_id = current_userd.id

      if @credit_card.update(credit_card_params)

        if @credit_card.status == 2
          @status = "Pending"

        elsif @credit_card.status == 1
          @status = "Approved"

        elsif @credit_card.status == 0
          @status = "Not Approved"
        end

        Watchdog.create(:user_id => current_userd.id,:added_by => current_userd.id,:controller => 'credit_cards', :action_page =>"update_credit_card",:foreign_id=>@credit_card.id ,:details=> "Credit Card has been updated by/"+ current_userd.username + " /with status/ " + @status + " /with number/ " + @credit_card.card_no )
        format.html { redirect_to @credit_card, notice: t('Credit card was successfully updated') }
        format.json { render :show, status: :ok, location: @credit_card }
      
      else
        Watchdog.create(:user_id => current_userd.id,:added_by => current_userd.id,:controller => 'credit_cards', :action_page =>"update_credit_card",:foreign_id=>@credit_card.id ,:details=> "Credit Card can't be updated by/"+ current_userd.username )
        format.html { render :edit }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      
      end
    end

    rescue => e
      @code = SecureRandom.hex

      @log =  ErrorsLog.create(:userd_id => current_userd.id,:error_msg => e.message.to_s,:error_code => @code.to_s) 
      redirect_to controller: 'frontendpages', action: 'error_page', id: @log.id
    end

  end

  # DELETE /credit_cards/1
  def destroy

    begin
    @credit_card.destroy

    respond_to do |format|
      Watchdog.create(:user_id => current_userd.id,:added_by => current_userd.id,:controller => 'credit_cards', :action_page =>"destroy_credit_card",:foreign_id=>@credit_card.id ,:details=> "Credit Card was successfully destroyed by/"+ current_userd.username )
      format.html { redirect_to credit_cards_url, notice: t('Credit card was successfully destroyed') }
      format.json { head :no_content }
    end

    rescue => e
      @code = SecureRandom.hex

      @log =  ErrorsLog.create(:userd_id => current_userd.id,:error_msg => e.message.to_s,:error_code => @code.to_s) 
      redirect_to controller: 'frontendpages', action: 'error_page', id: @log.id
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit_card
      @credit_card = CreditCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credit_card_params
      params.require(:credit_card).permit(:user_id, :name, :card_no, :card_type,:photo,:selfie, :expire_date)
    end
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/_form.html.erb
<%= form_for(@credit_card) do |f| %>
  <% if @credit_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credit_card.errors.count, "error") %> prohibited this credit_card from being saved:</h2>

      <ul>
      <% @credit_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :card_no %><br>
    <%= f.text_field :card_no %>
  </div>
  <div class="field">
    <%= f.label :card_type %><br>
    <%= f.text_field :card_type %>
  </div>
  <div class="field">
    <%= f.label :expire_date %><br>
    <%= f.date_select :expire_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/credit_cards/create.html.erb
<%= debug(params)%>

app/views/credit_cards/edit.html.erb
<h1>Editing Credit Card</h1>

<%= render 'form' %>

<%= link_to 'Show', @credit_card %> |
<%= link_to 'Back', credit_cards_path %>

app/views/credit_cards/index.html.erb
<% @number = "3530111333300000" %>
<% @detector = CreditCardValidations::Detector.new(@number) %>
<%# debug(@detector.brand) %>
<script>
    $('#bank-account').addClass('active');
    </script> 
    <% content_for :title, t('Credit Cards') %>
    <% content_for :icon, 'icon ic-icons-88' %>
    <section class="section mrg-bottom-sm padding-hor-lg bg-white pad-top-md pad-bottom-md s-boxshadow radius-light">
    <h3 class="page-icon lg-sm-fontsize text-dbrand mrg-bottom-sm hlf-e-btm">
      <img src="<%= format_link(request) %>/assets/imgs/wicon1.png" alt="wicon1">
    </h3>
    <div class="page-title l-height-md mrg-bottom-md">
      <div class="row row-default button-row">
          <div class="col-xs-6">
              <h4 class="iblock mrg-left-lg md-lg-fontsize text-dbrand font-weight-normal">
            <%= t('Credit Cards') %>
              </h4>
          </div>
          <div class="col-xs-6">
              <div class="text-left">
                  <%= link_to "<button type='button' class='btn text-hover-white text-white bg-black border-color-black md-padding radius-md'>#{t('New Credit Card')}</button>".html_safe, new_credit_card_path%>
              </div>
          </div>
      </div>
    </div>
    <div class="listing-section listing-section2">
    
    
    <div class="btm-bg-grd">
    <div class="height-490 content demo-y">
    
      <div class="selfscroll-section">
    
      <div class="row row-sm">
    
      <% @credit_cards.each do |credit_card| %>
    
          <div class="col-sm-12 col-md-6">
              <div class="listing-div hover-b-boxshadow">
                  <h4 class="icon-section">
                      <!-- <img src="credit-card-3.png" alt="icon"> -->

                      <%#  image_tag('/style/images/icon_'+credit_card.status.to_s+'.png')  %>

                     <img src="<%= format_link(request) %>/credit_card_banks/<%= credit_card.card_type.to_s %>.png" >

                     
                  </h4>
                  <h5 class="list-title text-blue font-bold sm-lg-fontsize mrg-bottom-xs">
                <%= credit_card.name %>   <%# credit_card.card_no %>  <%=  credit_card.card_no[0,4] %> <%= 'XXXXXXXX' %> <%= credit_card.card_no[12,16] %>
                    
                  </h5>
                  <p class="listing-d pos-relative font-bold color-gray pad-right-sm sm-sm-fontsize mrg-bottom-xs">
                      <i class="ico icon-wallet"></i>
                      <span class="mrg-right-xs">
                      <%= credit_card.created_at %>
                      
                      </span>
                  </p>
                  <div class="do-small-action">
                      <div class="dosm-visi text-left pointer">
                        <span class="iblock bg-gray radius-crlc"></span>
                        <span class="iblock bg-gray radius-crlc"></span>
                        <span class="iblock bg-gray radius-crlc"></span>
                      </div>
                      <div class="dosmall-action-div  bg-white l-shadow radius-lighter">
                        <ul class="dosmall-action-ul">
    
                            <li><%# link_to 'Edit', edit_credit_card_path(credit_card) %></li>
                            <li><a  href= "#" theid = '<%= credit_card.id %> ' class="deleteaccount"><%= t('Delete Account') %></a></li>
                            <%# link_to '<i class="fa fa-trash fa fa-white"></i>'.html_safe, credit_card, {  'data-toggle' => 'tooltip', 'data-confirm' => 'Are you sure you want to delete this ?', 'data-method' => 'delete', 'data-placement' =>'top', 'title' =>'Delete'} %>

                            <li><%= link_to t('Show Credit Card Details'), credit_card %></li>
    
                          </ul>
                        </div>
                  </div>
              </div>
          </div>
    
          <% end %>
          <%# will_paginate @users_banks, :previous_label => t("previous"), :next_label => t("next") %>
    
    
    
    
    
          </div>
          </div>
      </div>
      </div>
    
    </div>
    </section>



<div id="confirm_delete_popup" class="selfpopup" style="display:none;">
<div class="selfpopup-bg">
</div>
<div class="selfpopup-content">
    <div class="selfpopup-inner">
        <div class="selfpopup-middle">
            <div class="padding-all-sm">
                <div class="cart-balance selfpopup-caption">
                    <span class="close-popup"><i class="icon-Plus-white"></i></span>
                    <div class="bg-white padding-ver-lg pad-right-md pad-left-md radius-lighter">
                        <h4 class="icon-img-pp mrg-bottom-sm">
                            <img src="<%= format_link(request) %>/assets/imgs/error.png" alt="error">
                        </h4>
                        <h5 class="md-md-fontsize text-black font-bold mrg-bottom-sm"> <%= t('Are you sure you want to delete this ?')%></h5>
                        <p id ="failure-messege" class="sm-sm-fontsize text-dgray font-weight-normal mrg-bottom-md hlf-e-btm l-height-2">

                        </p>

                        <div class="self-btn-group mrg-top-md">
                            <div class="mrg-top-md">

                                    <a id = 'deletelink' class="mrg-left-xs btn bg-black radius-md hover-bg-brand text-white text-hover-white md-padding" rel="nofollow" data-method="delete" href="#"><i class="ico icon-white-logo"></i><%= t('yesss')%></a>


                                    <a href="#"  class="mrg-left-xs btn border-blue radius-md hover-bg-brand text-blue text-hover-white md-padding no_del">
                                    <%= t('nooo')%>   
                                </a>

                                
                                
                                
                
                               
                            </div>
                        </div>

                        <!-- <a href="#" class="btn md-padding radius-md border-brand text-brand text-hover-white hover-bg-brand">ةفاضإ ديصرلا</a> -->
                    </div>
                    <div class="crcl-animation">
                        <span class="lg-crcl"></span>
                        <span class="md-crcl"></span>
                        <span class="sm-crcl"></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>



<script>


$(document).ready(function() {

        $(".deleteaccount").click(function() {
            
                $('#confirm_delete_popup').show();
                    var id = $(this).attr("theid");
                    $('#deletelink').attr('href','/credit_cards/'+id);
                    
                     });


                     $(".no_del").click(function() {
            
            $('#confirm_delete_popup').hide();

                 });


                     


});
</script>
    