config/routes.rb
Rails.application.routes.draw do
  resources :withdraws_banks


  resources :credit_cards do
    member do
      get :credit_card_image
    end
  end

  

 devise_for :userds ,:path_names => {
	:verify_authy => "/verify-token",
	:enable_authy => "/enable-two-factor",
	:verify_authy_installation => "/verify-installation",

},

controllers: { registrations: "userds/registrations",passwords:"userds/passwords", sessions: "userds/sessions"  ,  invitations: "invitations", two_factor_authentication: "userds/two_factor_authentication",checkga:"userds/checkga",confirmations:"userds/confirmations"  } do
  
  match 'userds/sign_out' => "devise/sessions#destroy"
end



  resources :users_wallets_balances,:except => [:edit,:show,:index]
  resources :users_wallets_balances_frozens,:except => [:index]

  resources :balances_withdraws_statuses do
    member do
      get :withdraw_image
    end
  end
 
  resources :notifications,:except => [:new]
  
  resources :users_groups
  resources :email_templates

  resources :carts,:except => [:edit,:index]
  resources :company_balances
  resources :balances_withdraws
  resources :roles
  resources :cards
  
  resources :watchdogs
  resources :settings


  resources :tickets do
    member do
      get :ticket_image
    end
  end

  
  resources :users_banks
  
   resources :onlinebanks, only: [:show] 


  resources :customsdata
  resources :user_verifications
  resources :transactions
  



   
get 'test_limits' => 'userds#test_limits'

get "come_soon" => "credit_cards#come_soon"

get "getcardtype" => "credit_cards#getcardtype"

get "testniceselect" => "homedevise#testniceselect"
  
get 'userwallet_frozen' => "users_wallets_balances_frozens#userwallet_frozen_get"
  
get 'check_expenses' => "users_wallets_balances_frozens#check_expenses"

get 'payers_welcome' => "userds#payers_welcome"

get 'error_page' => "frontendpages#error_page"

get 'contact' => "frontendpages#contact"


post 'userds/password/forgot', to: 'userds#forgot'

post 'userds/password/reset', to: 'userds#reset'

get "backup_status" => "userds#backup_status"

get "resend_tfa" => "userds#resend_tfa"
post "resend_tfa" => "userds#resend_tfa"
patch "resend_tfa" => "userds#resend_tfa"
get "uniquetel" => "userds#uniquetel"
get "offline_avatar" => "onlinebanks#offline_avatar"
get "exception_ticket" => "onlinebanks#exception_ticket"

get "user_sms_check" => "userds#user_sms_check"
post "user_sms_check" => "userds#user_sms_check_post"

get "balance_with_draw_sms_check" => "balances_withdraws#balance_with_draw_sms_check"
post "balance_with_draw_sms_check" => "balances_withdraws#balance_with_draw_sms_check_post"

  
post "changeprofile" => "userds#changeprofile"
post "edituserprofile" => "user_verifications#edituserprofile"
get "withdraw_status_image" => "balances_withdraws_statuses#withdraw_status_image"


get "mailconfirm" => "user_verifications#mailconfirm" 

get "get_attachment/:id" => "attachments#get_attachment"
get "admin_attach/:id" => "admin_attachments#admin_attach"


get "verify_image" => "user_verifications#verify_image"

get "unlockconfirm" => "user_verifications#unlockconfirm"

get "verify_image" => "user_verifications#verify_image"
post "balances_withdraws/:id" => "balances_withdraws#update_hint"
  
get"searchpost" => "transactions#search"
post"searchpost" => "transactions#searchpost"

get "types" => "currencies_withdraw_ratios#types"
post "types" => "currencies_withdraw_ratios#types"
patch "types" => "currencies_withdraw_ratios#types"

get "currencies" => "currencies_withdraw_types#currencies"
post "currencies" => "currencies_withdraw_types#currencies"
patch "currencies" => "currencies_withdraw_types#currencies"


get "buycart" => "carts#buycart"
get "payment_method" => "carts#payment_method"

get "payment_method_ratios" => "carts#payment_method_ratios"


get "get_expenses" => "balances_withdraws#get_expenses"
get "get_previous" => "balances_withdraws#get_previous"

get "review_balance_withdraw" => "balances_withdraws#review_balance_withdraw"
post "review_balance_withdraw" => "balances_withdraws#review_balance_withdraw"

post "review_western_gram" => "balances_withdraws#review_western_gram"
get "review_western_gram" => "balances_withdraws#review_western_gram_get"
post "review_egyptian_mail" => "balances_withdraws#review_egyptian_mail"

get "sendsms" => "user_verifications#sendsms"
post "sendsms" => "user_verifications#sendsms_post"

get "sendvoicesms" => "user_verifications#sendvoicesms"
post "sendvoicesms" => "user_verifications#sendvoicesms_post"



get "help_center" => "tickets#help_center"

get "freshdesk" => "tickets#freshdesk"
post "freshdesk" => "tickets#freshdesk_post"

get "send2fasms" => "user_verifications#send2fasms"

get "resendsms" => "user_verifications#resendsms"
get "verifysms" => "user_verifications#verifysms"
get "veriffysms" => "user_verifications#veriffysms" 
get "resendsmsa2" => "user_verifications#resendsmsa2"

post "changetel" => "user_verifications#changetel"

get "user_wallets_transactions" => "transactions#user_wallets_transactions"

get "pre_verification" => "user_verifications#pre_verification"
get "all_verifications" => "user_verifications#all_verifications"

get "visa_activate" => "user_verifications#visa_activate"
get "address_activate" => "user_verifications#address_activate"
get "selfie_activate" => "user_verifications#selfie_activate"

get "exceptionmessage" => "balances_withdraws#exceptionmessage"
post "exceptionmessage" => "balances_withdraws#exceptionmessage"
patch "exceptionmessage" => "balances_withdraws#exceptionmessage"

get "balances_withdraws_methods" => "balances_withdraws#methods"
post "balances_withdraws_methods" => "balances_withdraws#methods"
patch "balances_withdraws_methods" => "balances_withdraws#methods"

post "searchpostbank" => "users_banks#searchpost"

get "users_banks_methods" => "users_banks#methods"
post "users_banks_methods" => "users_banks#methods"
patch "users_banks_methods" => "users_banks#methods"

get "users_banks_types" => "users_banks#types"
post "users_banks_types" => "users_banks#types"
patch "users_banks_types" => "users_banks#types"

get "users_banks_currencies" => "users_banks#currencies"
post "users_banks_currencies" => "users_banks#currencies"
patch "users_banks_currencies" => "users_banks#currencies"

post "add_bank_confirm" => "users_banks#add_bank_confirm"

get "review_egyptian_mail_post" => "users_banks#review_egyptian_mail"
post "review_egyptian_mail_post" => "users_banks#review_egyptian_mail_post"

get "review_new_bank" => "users_banks#new_review"

post "review_new_bank" => "users_banks#new_review_post"
patch "review_new_bank" => "users_banks#new_review_post"

get "users_banks_egyptian_mail" => "users_banks#egyptian_mail"
get "edit_egyptian_mail_bank" => "users_banks#edit_egyptian_mail_bank"
post "edit_egyptian_mail_bank" => "users_banks#edit_egyptian_mail_bank"
get "users_banks_western_gram" => "users_banks#western_gram"

get "users_banks/:id/edit_egyptian_mail" => "users_banks#edit_egyptian_mail", as: "edit_egyptian_mail"

get "users_banks/:id/edit_western_gram" => "users_banks#edit_western_gram", as: "edit_western_gram"
get "users_banks/:id/edit_bank" => "users_banks#edit_bank", as: "edit_bank"

post  'users_banks_save_western_gram' => 'users_banks#save_western_gram'
post "edit_western" => "users_banks#post_edit_western"
patch "edit_western" => "users_banks#post_edit_western"

post "users_banks_save_bank" => "users_banks#post_edit_western"

post "edit_egyptian_mail" => "users_banks#post_edit_egyptianmail"
patch "edit_egyptian_mail" => "users_banks#post_edit_egyptianmail"

post  'users_banks_save_egyptian_mail' => 'users_banks#save_egyptian_mail'

post  'users_bankssave' => 'users_banks#save'
get  'users_bankssave' => 'users_banks#getsave'

###########################################

post "id_activate" => "user_verifications#update"
patch "id_activate" => "user_verifications#update"

get 'homepages/home'

root 'userds#account_settings' 
get "welcome" => "welcome#welcome"
   
get "account_settings" => "userds#account_settings"
get "user_profile" => "userds#user_profile"
get "log_operations" => "userds#log_operations"
get "fail_signin" => "userds#fail_signin"
get "failed_operations" => "userds#failed_operations"
get "userstatistics" => "userds#userstatistics"
get "allusers" => "userds#index"

put "account_settings" => "userds#set_account_info"

get "useractive" => "userds#uactive"

get "change_locale" => "userds#change_locale"

get "sms_deactivate" => "user_verifications#sms_deactivate"
get "sms_activate" => "user_verifications#sms_activate"

post "sms_activate" => "user_verifications#sms_activate_post"

post "email_activate_post" => "user_verifications#email_activate_post"

get "active_otp_secret" => "user_verifications#active_otp_secret"

get "previousattachments" => "user_verifications#previous_attachments"

get "closeticket" => "tickets#closeticket"

get "listticket" => "tickets#index"

get "ticketreply" => "tickets#replay"
post "ticketreply" => "tickets#create"

get "ubankaccount" => "users_banks#useraccounts"

get "users_banks_main" => "users_banks#main_bank"

post "users_banks_main" => "users_banks#main_bank_post"

get "balances_withdraws_main" => "balances_withdraws#main"

get "egyptian_mail" => "balances_withdraws#egyptian_mail"

get "edit_bank_conversion" => "users_banks#edit_bank_conversion"

get "western_gram" => "balances_withdraws#western_gram"

post  'save_western_gram' => 'balances_withdraws#save_western_gram'

post  'save_egyptian_mail' => 'balances_withdraws#save_egyptian_mail'

get 'operations_details' => 'users_wallets_balances#operations_details'

post  'balancewithdrawsave' => 'balances_withdraws#save'
get 'userbankdids' => 'users_banks#for_balanceop'
get 'userwallets' => 'users_wallets_balances#walletselection'
get 'walletfrozen' => 'users_wallets_balances_frozens#walletfrozen'

get 'mailstatus' => 'users_wallets_balances_frozens#mailstatus'
get 'namestatus' => 'users_wallets_balances_frozens#namestatus'

app/controllers/currencies_withdraw_types_controller.rb
class CurrenciesWithdrawTypesController < ApplicationController
  before_action :set_currencies_withdraw_type, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_userd! 
  
  # GET /currencies_withdraw_types
  def index

    begin
    if current_userd.role_id == 1
      @currencies_withdraw_types = CurrenciesWithdrawType.all
    end

    rescue =>e
      @code = SecureRandom.hex

      @log =  ErrorsLog.create(:userd_id => current_userd.id,:error_msg => e.message.to_s,:error_code => @code.to_s) 
      redirect_to controller: 'frontendpages', action: 'error_page', id: @log.id
    end

  end

  def currencies 

    begin
    @wallets=UsersWalletsBalance.where(user_id: current_userd.id,status: 1)

    rescue =>e
      @code = SecureRandom.hex

      @log =  ErrorsLog.create(:userd_id => current_userd.id,:error_msg => e.message.to_s,:error_code => @code.to_s) 
      redirect_to controller: 'frontendpages', action: 'error_page', id: @log.id
    end
  
  end

  def show
  end

  # GET /currencies_withdraw_types/new
  def new

    begin
    if current_userd.role_id == 1
      @currencies_withdraw_type = CurrenciesWithdrawType.new
    end

    rescue =>e
      @code = SecureRandom.hex

      @log =  ErrorsLog.create(:userd_id => current_userd.id,:error_msg => e.message.to_s,:error_code => @code.to_s) 
      redirect_to controller: 'frontendpages', action: 'error_page', id: @log.id
    end

  end

  # GET /currencies_withdraw_types/edit
  def edit
  end

  # POST /currencies_withdraw_types/create
  def create

    begin
    if current_userd.role_id == 1
    @currencies_withdraw_type = CurrenciesWithdrawType.new(currencies_withdraw_type_params)

      respond_to do |format|

        if @currencies_withdraw_type.save
          format.html { redirect_to @currencies_withdraw_type, notice: 'Currencies withdraw type was successfully created.' }
          format.json { render :show, status: :created, location: @currencies_withdraw_type }
        else
          format.html { render :new }
          format.json { render json: @currencies_withdraw_type.errors, status: :unprocessable_entity }
        end
        
      end

    end

    rescue =>e
      @code = SecureRandom.hex

      @log =  ErrorsLog.create(:userd_id => current_userd.id,:error_msg => e.message.to_s,:error_code => @code.to_s) 
      redirect_to controller: 'frontendpages', action: 'error_page', id: @log.id
    end

  end

  # Update /currencies_withdraw_types/
  def update

    begin
    if current_userd.role_id == 1

      respond_to do |format|

        if @currencies_withdraw_type.update(currencies_withdraw_type_params)
          format.html { redirect_to @currencies_withdraw_type, notice: 'Currencies withdraw type was successfully updated.' }
          format.json { render :show, status: :ok, location: @currencies_withdraw_type }
        else
          format.html { render :edit }
          format.json { render json: @currencies_withdraw_type.errors, status: :unprocessable_entity }
        end

      end

    end

    rescue =>e
      @code = SecureRandom.hex

      @log =  ErrorsLog.create(:userd_id => current_userd.id,:error_msg => e.message.to_s,:error_code => @code.to_s) 
      redirect_to controller: 'frontendpages', action: 'error_page', id: @log.id
    end

  end

  # DELETE /currencies_withdraw_types
  def destroy

    begin
    if current_userd.role_id == 1
      @currencies_withdraw_type.destroy

      respond_to do |format|
      format.html { redirect_to currencies_withdraw_types_url, notice: 'Currencies withdraw type was successfully destroyed.' }
      format.json { head :no_content }
      end

    end

    rescue =>e
      @code = SecureRandom.hex

      @log =  ErrorsLog.create(:userd_id => current_userd.id,:error_msg => e.message.to_s,:error_code => @code.to_s) 
      redirect_to controller: 'frontendpages', action: 'error_page', id: @log.id
    end

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_currencies_withdraw_type
      @currencies_withdraw_type = CurrenciesWithdrawType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def currencies_withdraw_type_params
      params.require(:currencies_withdraw_type).permit(:name,:currency_code,:logo,:country_code)
    end

end

app/helpers/currencies_withdraw_types_helper.rb
module CurrenciesWithdrawTypesHelper
end

app/views/currencies_withdraw_types/_form.html.erb
<%= form_for(@currencies_withdraw_type) do |f| %>
  <% if @currencies_withdraw_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@currencies_withdraw_type.errors.count, "error") %> prohibited this currencies_withdraw_type from being saved:</h2>

      <ul>
      <% @currencies_withdraw_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :currency_code %><br>
    <%= f.text_field :currency_code %>
  </div>
  <p>
    <%= f.label t('صورة لوجو') %><br />
    <%= f.file_field  :logo,:class => 'form-control' %>
  </p>

  <div class="field">
    <%= f.label :country_code %><br>
    <%= f.text_field :country_code %>
  </div>
  
  <div class="field">
    <%= f.label :currencies_withdraw_ratios_id %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/currencies_withdraw_types/currencies.html.erb
<h2>العملات المتاح السحب منها علي اساس المحافظ المنشأة</h2>

<div class="table-rep-plugin"><div class="table-responsive" data-pattern="priority-columns">

<table id="datatable" class="table  table-stylish">
  <thead>
    <tr>
      <th>اسم العملة</th>
      <th>اسم المحفظة المسحوب منها</th>
      <th>Currencies Code</th>
      <th>Logo</th>

      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @wallets.each do |wallet| %>

      <tr>
            <%  @thecurrency = CurrenciesWithdrawType.where(currency_code: wallet.currency).first %>

        <td><%= @thecurrency.name %></td>
        <td><%= wallet.wallet_name %></td>
        <td><%= wallet.currency %></td>
    <td><%= image_tag @thecurrency.logo.url %></td>

<td><%= link_to 'استخدم هذه العملة', types_path(:id =>@thecurrency.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<h6>اذا كنت تريد عملات اخري للسحب برجاء</h6>
<%= link_to "<button type='button' class='btn btn-wide btn-primary'><span class='btn-label'><i class='fa fa-plus'></i> </span>#{t('انشاء محفظة جديدة')}</button>".html_safe, new_users_wallets_balance_path , { :class=>'linktop' } %>

</div></div>

app/views/currencies_withdraw_types/edit.html.erb
<h1>Editing Currencies Withdraw Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @currencies_withdraw_type %> |
<%= link_to 'Back', currencies_withdraw_types_path %>

app/views/currencies_withdraw_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Currencies Withdraw Types</h1>

<div class="table-rep-plugin"><div class="table-responsive" data-pattern="priority-columns">

<table id="datatable" class="table  table-stylish">
  <thead>
    <tr>
      <th>Name</th>
      <th>Currencies Code</th>
      <th>Logo</th>
            <th>Country Code</th>


      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @currencies_withdraw_types.each do |currencies_withdraw_type| %>
      <tr>
        <td><%= currencies_withdraw_type.name %></td>
        <td><%= currencies_withdraw_type.currency_code %></td>
    <td><%= image_tag currencies_withdraw_type.logo.url %></td>
        <td><%= currencies_withdraw_type.country_code %></td>

        <td><%= link_to 'Show', currencies_withdraw_type %></td>
        <td><%= link_to 'Edit', edit_currencies_withdraw_type_path(currencies_withdraw_type) %></td>
        <td><%= link_to 'Destroy', currencies_withdraw_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div></div>
<br>

<%= link_to 'New Currencies withdraw type', new_currencies_withdraw_type_path %>

app/views/currencies_withdraw_types/new.html.erb
<h1>New Currencies Withdraw Type</h1>

<%= render 'form' %>

<%= link_to 'Back', currencies_withdraw_types_path %>

app/views/currencies_withdraw_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @currencies_withdraw_type.name %>
</p>

<p>
  <strong>Currencies withdraw ratios:</strong>
</p>

<%= link_to 'Edit', edit_currencies_withdraw_type_path(@currencies_withdraw_type) %> |
<%= link_to 'Back', currencies_withdraw_types_path %>