config/routes.rb
Rails.application.routes.draw do
  resources :withdraws_banks


  resources :credit_cards do
    member do
      get :credit_card_image
    end
  end

  

 devise_for :userds ,:path_names => {
	:verify_authy => "/verify-token",
	:enable_authy => "/enable-two-factor",
	:verify_authy_installation => "/verify-installation",

},

controllers: { registrations: "userds/registrations",passwords:"userds/passwords", sessions: "userds/sessions"  ,  invitations: "invitations", two_factor_authentication: "userds/two_factor_authentication",checkga:"userds/checkga",confirmations:"userds/confirmations"  } do
  
  match 'userds/sign_out' => "devise/sessions#destroy"
end



  resources :users_wallets_balances,:except => [:edit,:show,:index]
  resources :users_wallets_balances_frozens,:except => [:index]

  resources :balances_withdraws_statuses do
    member do
      get :withdraw_image
    end
  end
 
  resources :notifications,:except => [:new]
  
  resources :users_groups
  resources :email_templates

  resources :carts,:except => [:edit,:index]
  resources :company_balances
  resources :balances_withdraws
  resources :roles
  resources :cards
  
  resources :watchdogs
  resources :settings


  resources :tickets do
    member do
      get :ticket_image
    end
  end

  
  resources :users_banks
  
   resources :onlinebanks, only: [:show] 


  resources :customsdata
  resources :user_verifications
  resources :transactions
  



   
get 'test_limits' => 'userds#test_limits'

get "come_soon" => "credit_cards#come_soon"

get "getcardtype" => "credit_cards#getcardtype"

get "testniceselect" => "homedevise#testniceselect"
  
get 'userwallet_frozen' => "users_wallets_balances_frozens#userwallet_frozen_get"
  
get 'check_expenses' => "users_wallets_balances_frozens#check_expenses"

get 'payers_welcome' => "userds#payers_welcome"

get 'error_page' => "frontendpages#error_page"

get 'contact' => "frontendpages#contact"


post 'userds/password/forgot', to: 'userds#forgot'

post 'userds/password/reset', to: 'userds#reset'

get "backup_status" => "userds#backup_status"

get "resend_tfa" => "userds#resend_tfa"
post "resend_tfa" => "userds#resend_tfa"
patch "resend_tfa" => "userds#resend_tfa"
get "uniquetel" => "userds#uniquetel"
get "offline_avatar" => "onlinebanks#offline_avatar"
get "exception_ticket" => "onlinebanks#exception_ticket"

get "user_sms_check" => "userds#user_sms_check"
post "user_sms_check" => "userds#user_sms_check_post"

get "balance_with_draw_sms_check" => "balances_withdraws#balance_with_draw_sms_check"
post "balance_with_draw_sms_check" => "balances_withdraws#balance_with_draw_sms_check_post"

  
post "changeprofile" => "userds#changeprofile"
post "edituserprofile" => "user_verifications#edituserprofile"
get "withdraw_status_image" => "balances_withdraws_statuses#withdraw_status_image"


get "mailconfirm" => "user_verifications#mailconfirm" 

get "get_attachment/:id" => "attachments#get_attachment"
get "admin_attach/:id" => "admin_attachments#admin_attach"


get "verify_image" => "user_verifications#verify_image"

get "unlockconfirm" => "user_verifications#unlockconfirm"

get "verify_image" => "user_verifications#verify_image"
post "balances_withdraws/:id" => "balances_withdraws#update_hint"
  
get"searchpost" => "transactions#search"
post"searchpost" => "transactions#searchpost"

get "types" => "currencies_withdraw_ratios#types"
post "types" => "currencies_withdraw_ratios#types"
patch "types" => "currencies_withdraw_ratios#types"

get "currencies" => "currencies_withdraw_types#currencies"
post "currencies" => "currencies_withdraw_types#currencies"
patch "currencies" => "currencies_withdraw_types#currencies"


get "buycart" => "carts#buycart"
get "payment_method" => "carts#payment_method"

get "payment_method_ratios" => "carts#payment_method_ratios"


get "get_expenses" => "balances_withdraws#get_expenses"
get "get_previous" => "balances_withdraws#get_previous"

get "review_balance_withdraw" => "balances_withdraws#review_balance_withdraw"
post "review_balance_withdraw" => "balances_withdraws#review_balance_withdraw"

post "review_western_gram" => "balances_withdraws#review_western_gram"
get "review_western_gram" => "balances_withdraws#review_western_gram_get"
post "review_egyptian_mail" => "balances_withdraws#review_egyptian_mail"

get "sendsms" => "user_verifications#sendsms"
post "sendsms" => "user_verifications#sendsms_post"

get "sendvoicesms" => "user_verifications#sendvoicesms"
post "sendvoicesms" => "user_verifications#sendvoicesms_post"



get "help_center" => "tickets#help_center"

get "freshdesk" => "tickets#freshdesk"
post "freshdesk" => "tickets#freshdesk_post"

get "send2fasms" => "user_verifications#send2fasms"

get "resendsms" => "user_verifications#resendsms"
get "verifysms" => "user_verifications#verifysms"
get "veriffysms" => "user_verifications#veriffysms" 
get "resendsmsa2" => "user_verifications#resendsmsa2"

post "changetel" => "user_verifications#changetel"

get "user_wallets_transactions" => "transactions#user_wallets_transactions"

get "pre_verification" => "user_verifications#pre_verification"
get "all_verifications" => "user_verifications#all_verifications"

get "visa_activate" => "user_verifications#visa_activate"
get "address_activate" => "user_verifications#address_activate"
get "selfie_activate" => "user_verifications#selfie_activate"

get "exceptionmessage" => "balances_withdraws#exceptionmessage"
post "exceptionmessage" => "balances_withdraws#exceptionmessage"
patch "exceptionmessage" => "balances_withdraws#exceptionmessage"

get "balances_withdraws_methods" => "balances_withdraws#methods"
post "balances_withdraws_methods" => "balances_withdraws#methods"
patch "balances_withdraws_methods" => "balances_withdraws#methods"

post "searchpostbank" => "users_banks#searchpost"

get "users_banks_methods" => "users_banks#methods"
post "users_banks_methods" => "users_banks#methods"
patch "users_banks_methods" => "users_banks#methods"

get "users_banks_types" => "users_banks#types"
post "users_banks_types" => "users_banks#types"
patch "users_banks_types" => "users_banks#types"

get "users_banks_currencies" => "users_banks#currencies"
post "users_banks_currencies" => "users_banks#currencies"
patch "users_banks_currencies" => "users_banks#currencies"

post "add_bank_confirm" => "users_banks#add_bank_confirm"

get "review_egyptian_mail_post" => "users_banks#review_egyptian_mail"
post "review_egyptian_mail_post" => "users_banks#review_egyptian_mail_post"

get "review_new_bank" => "users_banks#new_review"

post "review_new_bank" => "users_banks#new_review_post"
patch "review_new_bank" => "users_banks#new_review_post"

get "users_banks_egyptian_mail" => "users_banks#egyptian_mail"
get "edit_egyptian_mail_bank" => "users_banks#edit_egyptian_mail_bank"
post "edit_egyptian_mail_bank" => "users_banks#edit_egyptian_mail_bank"
get "users_banks_western_gram" => "users_banks#western_gram"

get "users_banks/:id/edit_egyptian_mail" => "users_banks#edit_egyptian_mail", as: "edit_egyptian_mail"

get "users_banks/:id/edit_western_gram" => "users_banks#edit_western_gram", as: "edit_western_gram"
get "users_banks/:id/edit_bank" => "users_banks#edit_bank", as: "edit_bank"

post  'users_banks_save_western_gram' => 'users_banks#save_western_gram'
post "edit_western" => "users_banks#post_edit_western"
patch "edit_western" => "users_banks#post_edit_western"

post "users_banks_save_bank" => "users_banks#post_edit_western"

post "edit_egyptian_mail" => "users_banks#post_edit_egyptianmail"
patch "edit_egyptian_mail" => "users_banks#post_edit_egyptianmail"

post  'users_banks_save_egyptian_mail' => 'users_banks#save_egyptian_mail'

post  'users_bankssave' => 'users_banks#save'
get  'users_bankssave' => 'users_banks#getsave'

###########################################

post "id_activate" => "user_verifications#update"
patch "id_activate" => "user_verifications#update"

get 'homepages/home'

root 'userds#account_settings' 
get "welcome" => "welcome#welcome"
   
get "account_settings" => "userds#account_settings"
get "user_profile" => "userds#user_profile"
get "log_operations" => "userds#log_operations"
get "fail_signin" => "userds#fail_signin"
get "failed_operations" => "userds#failed_operations"
get "userstatistics" => "userds#userstatistics"
get "allusers" => "userds#index"

put "account_settings" => "userds#set_account_info"

get "useractive" => "userds#uactive"

get "change_locale" => "userds#change_locale"

get "sms_deactivate" => "user_verifications#sms_deactivate"
get "sms_activate" => "user_verifications#sms_activate"

post "sms_activate" => "user_verifications#sms_activate_post"

post "email_activate_post" => "user_verifications#email_activate_post"

get "active_otp_secret" => "user_verifications#active_otp_secret"

get "previousattachments" => "user_verifications#previous_attachments"

get "closeticket" => "tickets#closeticket"

get "listticket" => "tickets#index"

get "ticketreply" => "tickets#replay"
post "ticketreply" => "tickets#create"

get "ubankaccount" => "users_banks#useraccounts"

get "users_banks_main" => "users_banks#main_bank"

post "users_banks_main" => "users_banks#main_bank_post"

get "balances_withdraws_main" => "balances_withdraws#main"

get "egyptian_mail" => "balances_withdraws#egyptian_mail"

get "edit_bank_conversion" => "users_banks#edit_bank_conversion"

get "western_gram" => "balances_withdraws#western_gram"

post  'save_western_gram' => 'balances_withdraws#save_western_gram'

post  'save_egyptian_mail' => 'balances_withdraws#save_egyptian_mail'

get 'operations_details' => 'users_wallets_balances#operations_details'

post  'balancewithdrawsave' => 'balances_withdraws#save'
get 'userbankdids' => 'users_banks#for_balanceop'
get 'userwallets' => 'users_wallets_balances#walletselection'
get 'walletfrozen' => 'users_wallets_balances_frozens#walletfrozen'

get 'mailstatus' => 'users_wallets_balances_frozens#mailstatus'
get 'namestatus' => 'users_wallets_balances_frozens#namestatus'

app/views/transactions/download.csv.erb

<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
        <%# @posts=params[:posts] %>

    <Table>
      <Row>
        <Cell><Data ss:Type="String"> Transaction ID</Data></Cell>
        <Cell><Data ss:Type="String">from</Data></Cell>
        <Cell><Data ss:Type="String">to</Data></Cell>
        <Cell><Data ss:Type="String">value_from</Data></Cell>
        <Cell><Data ss:Type="String">w_from_name</Data></Cell>
        <Cell><Data ss:Type="String"> w_from_balance_before</Data></Cell>
        <Cell><Data ss:Type="String">w_from_balance_after</Data></Cell>
        <Cell><Data ss:Type="String">value_to</Data></Cell>
        <Cell><Data ss:Type="String">w_to_name</Data></Cell>
        <Cell><Data ss:Type="String">w_to_balance_before</Data></Cell>
        <Cell><Data ss:Type="String">w_to_balance_after</Data></Cell>
        <Cell><Data ss:Type="String">beforecharge</Data></Cell>
        <Cell><Data ss:Type="String">description</Data></Cell>
        <Cell><Data ss:Type="String">created_at</Data></Cell>
      </Row>
    <% @posts.each do |posts| %>
      <Row>
        <Cell><Data ss:Type="String"><%= posts.transaction_id %></Data></Cell>
        <% @uid = Userd.where("id =?",posts.user_id).first%>
        <% @uidto = Userd.where("id =?",posts.user_id_to).first%>
        <Cell><Data ss:Type="String"><%= @uid.name %></Data></Cell>
        <%if @uidto != nil %>
        <Cell><Data ss:Type="String"><%= @uidto.name %></Data></Cell>
        <% else%>
        <Cell><Data ss:Type="String"><%= " " %></Data></Cell>
        <% end %>
        <Cell><Data ss:Type="Number"><%= posts.value_from %></Data></Cell>
        <Cell><Data ss:Type="String"><%= posts.w_from_name %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= posts.w_from_balance_before %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= posts.w_from_balance_after %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= posts.value_to %></Data></Cell>
        <Cell><Data ss:Type="String"><%= posts.w_to_name %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= posts.w_to_balance_before %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= posts.w_to_balance_after %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= posts.beforecharge %></Data></Cell>
        <Cell><Data ss:Type="String"><%= posts.description %></Data></Cell>
        <Cell><Data ss:Type="String"><%= posts.created_at %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/transactions/download.html.erb
<%= form_tag  url_for(:controller => 'transactions', :action => 'downloadpost'), :method => 'post' do %>

<div class="field">
  <%= select_tag(:statustyp, options_for_select([['inner_transactions'],['outer_transactions']],:selected => params[:option]),:required => true,  class: 'form-control' )   %>
  </div>

  <br>
  <div class="field">
  <%= select_tag(:searchtime, options_for_select([['last hour'],['last day'], ['last week'], ['last month'],['last year']],:selected => params[:option]), :required => true,  class: 'form-control' )   %>
  </div>
  
	<br>
  
    <div class="actions  text-center"> 
 
<button type="submit" class="btn btn-primary waves-effect waves-light m-t-15 text-center"><%= t('Search') %> </button>
</div>
  
<% end %>



<!-- 
<p>
  Download:
  <%# link_to "CSV", downloads_path(format: "csv"),:method => :post %> |
  <%# link_to "Excel", downloads_path(format: "xls"),:method => :post %>
</p> -->

app/views/transactions/download.xls.erb

<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
        <%# @posts=params[:posts] %>

    <Table>
      <Row>
        <Cell><Data ss:Type="String"> Transaction ID</Data></Cell>
        <Cell><Data ss:Type="String">from</Data></Cell>
        <Cell><Data ss:Type="String">to</Data></Cell>
        <Cell><Data ss:Type="String">value_from</Data></Cell>
        <Cell><Data ss:Type="String">w_from_name</Data></Cell>
        <Cell><Data ss:Type="String"> w_from_balance_before</Data></Cell>
        <Cell><Data ss:Type="String">w_from_balance_after</Data></Cell>
        <Cell><Data ss:Type="String">value_to</Data></Cell>
        <Cell><Data ss:Type="String">w_to_name</Data></Cell>
        <Cell><Data ss:Type="String">w_to_balance_before</Data></Cell>
        <Cell><Data ss:Type="String">w_to_balance_after</Data></Cell>
        <Cell><Data ss:Type="String">beforecharge</Data></Cell>
        <Cell><Data ss:Type="String">description</Data></Cell>
        <Cell><Data ss:Type="String">created_at</Data></Cell>
      </Row>
    <% @posts.each do |posts| %>
      <Row>
        <Cell><Data ss:Type="String"><%= posts.transaction_id %></Data></Cell>
        <% @uid = Userd.where("id =?",posts.user_id).first%>
        <% @uidto = Userd.where("id =?",posts.user_id_to).first%>
        <Cell><Data ss:Type="String"><%= @uid.name %></Data></Cell>
        <%if @uidto != nil %>
        <Cell><Data ss:Type="String"><%= @uidto.name %></Data></Cell>
        <% else%>
        <Cell><Data ss:Type="String"><%= " " %></Data></Cell>
        <% end %>
        <Cell><Data ss:Type="Number"><%= posts.value_from %></Data></Cell>
        <Cell><Data ss:Type="String"><%= posts.w_from_name %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= posts.w_from_balance_before %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= posts.w_from_balance_after %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= posts.value_to %></Data></Cell>
        <Cell><Data ss:Type="String"><%= posts.w_to_name %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= posts.w_to_balance_before %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= posts.w_to_balance_after %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= posts.beforecharge %></Data></Cell>
        <Cell><Data ss:Type="String"><%= posts.description %></Data></Cell>
        <Cell><Data ss:Type="String"><%= posts.created_at %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/transactions/downloadpost.html.erb
<%= form_tag  downloads_path(format: "xls"), :method => 'post' do %>


  <%= hidden_field_tag :statustyp, params[:transactionsearch][:statustyp] %>
  
  <%= hidden_field_tag :searchtime, params[:transactionsearch][:searchtime] %>
  
  
    <div class="actions  text-center"> 
 
<button type="submit" class="btn btn-primary waves-effect waves-light m-t-15 text-center">Download Xls </button>
</div>
  
<% end %>
<br>



<%= form_tag  downloads_path(format: "csv"), :method => 'post' do %>
  
  
    <%= hidden_field_tag :statustyp, params[:transactionsearch][:statustyp] %>
    
    <%= hidden_field_tag :searchtime, params[:transactionsearch][:searchtime] %>
    
    
      <div class="actions  text-center"> 
   
  <button type="submit" class="btn btn-primary waves-effect waves-light m-t-15 text-center">Download CSV </button>
  </div>
    
  <% end %>



<%# debug @posts%>
<%# debug params[:transactionsearch]%>



<p>
  Download:
  <%# link_to "CSV", downloads_path(format: "csv"),:method => :post %> |
  
  <%# link_to "CSV", downloads_path(format: "csv"),:method => :post %> |
  <%# link_to "Excel", downloads_path(format: "xls") %>
</p>

app/views/transactions/searchpost.html.erb
<!-- 
            <section id="main" class="section mrg-bottom-sm padding-hor-lg bg-white pad-top-md pad-bottom-md s-boxshadow radius-light">
            <h3 class="page-icon lg-sm-fontsize text-dbrand mrg-bottom-sm hlf-e-btm">
                <i class="ico icon-Support"></i>
            </h3>
            <div class="page-title l-height-md mrg-bottom-md">
                <div class="row row-default button-row">
                    <div class="col-md-3">
                        <h4 class="iblock mrg-left-lg md-lg-fontsize text-dbrand font-weight-normal">

                       <%= t('Balance Operations') %>
                     
                        </h4>
                    </div>
                    <%= form_tag  url_for(:controller => 'transactions', :action => 'searchpost'), :method => 'post' do %>
                        
                    <div class="col-md-9">
                        <div class="clearfix">
                            
                            <div class="search-div radius-md bg-white b-boxshadow">
                                <input type="text" name="search" class="text-dgray sm-md-fontsize" placeholder=<%= t('Search') %>>

                                <button type="submit" class="search-btn"><i class="icon ic-search-1"></i></button>
                                
                            </div>
                            <div class="self-select bg-white radius-md mrg-left-xs datepicker">
                                        <%= select_tag(:searchtime, options_for_select([[t('last hour'),'last hour'],[t('last day'),'last day'], [t('last week'),'last week'], [t('last month'),'last month'],[t('last year'),'last year']],:selected => params[:option]),:include_blank => ' date' , class: 'selectpicker' )   %>
                                    </div>
                                    <div class="self-select bg-white radius-md mrg-left-xs ppicker">
                                        <%= select_tag(:operationtyp, options_for_select([[t('Buy Cart'),'onlinebanks'],[t('Cart Charge'),'carts'], [t('Balance Transfer To Other Users'),'users_wallets_balances_frozens'], [t('Balance Transfer Between Wallets'),'users_wallets_balances'],[t('Withdraw Requests'),'balances_withdraw']],:selected => params[:option]),:include_blank => ' operation type',  class: 'selectpicker' )   %>
                                    </div>
                        </div>
                    </div>
                </div>
            </div>
            <% end %>

            <% if @tickets != nil %>
            
            <div class="listing-section listing-section2">
              
                <div class="row row-sm">
                <% @tickets.each do |ticket| %>
                  
                    <div class="col-md-6 col-sm-6 padding-hor-sm">
                      
                        <div class="listing-div hover-b-boxshadow tck-name">
                            <h4 class="icon-section">
                                <img src="resources/imgs/user-notification.png" alt="usr" class="imagecover">
                            </h4>
                            <h5 class="list-title text-blue font-bold sm-lg-fontsize mrg-bottom-xs">
                
                            <%= ticket.description %>
                            
                            </h5>
                            <p class="listing-d pos-relative english-font font-bold color-gray pad-right-sm sm-sm-fontsize mrg-bottom-xs">
                                <i class="ico icon-calendar"></i><%= ticket.created_at.strftime('%H:%M:%S%p at %d/%m/%Y') %>
                            </p>
                            <div class="do-small-action">
                                        <div class="dosm-visi text-left pointer">
                                            <span class="iblock bg-gray radius-crlc"></span>
                                            <span class="iblock bg-gray radius-crlc"></span>
                                            <span class="iblock bg-gray radius-crlc"></span>
                                        </div>
                                        <div class="dosmall-action-div  bg-white l-shadow radius-lighter">
                                            <ul class="dosmall-action-ul">
                                                <li><a href="/help_center"><%= t('Report a problem')%></a>
                                                </li>
                                                <li><a href="#"><%= t('Download bill')%></a>
                                                </li>
                                                <% if params[:operationtyp] == "onlinebanks" %>
                                                <li><a id="cart_details" href=<%= "/cartgen/" + ticket.id.to_s %>><%= t('Show details')%></a>
                                                </li>
                                                <% else %>
                                                <li><a href="#"><%= t('Show details')%></a>
                                                </li>
                                                 <% end %>
                                                 
                                            </ul>
                                        </div>
                                    </div>
                        </div>
                    </div>
                    <% end %>
                    <%# will_paginate @tickets, :previous_label => t("previous"), :next_label => t("next") %>
                    <%# will_paginate @tickets,:param_name => 'page', :previous_label => t("previous"), :next_label => t("next") %>
                   
                </div>
            </div>
            <% end %>
        </section>
        
        <div id="data" >
           
        </div>


        <script>
                $(document).ready(function(){
                    
                $("#cart_details").click(function()
                {
                                    

               
              // $("#cart-balance").show();
               var id =  $("#cart_details").attr('href');
               var re= id +" "+ "#cart-balance";
              //$( "#data" ).load(re);
                

              $( "#data" ).load( re , function() {
                
                     
                   
                      $.getScript("/assets/js/app.js");
                    
                 
                  
                  });
                
                  
                
               //console.log(id);
               return false;
               
                });

                });
            </script> -->

app/views/transactions/user_wallets_transactions.html.erb
<p id="notice"><%= notice %></p>

<br>

<%# @token1 %><br>
<%# @number %><br>
<%# @trans_id2 %><br>
<%# @trans_id4 %><br>

<% if @transactions != nil %>
<h1>سجل عمليات لتحويل من محفظه لمحفظه</h1>

<div class="table-rep-puginl"><table id="datatable" class="table  table-stylish">
  <thead>
    <tr>
      <th>Transaction ID</th>
      
      <th>description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.transaction_id %></td>
        
        <td><%= transaction.description %></td>
        
        <td><%= link_to 'Show', transaction %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>
<div class="pagination">
<%= will_paginate @transactions,:param_name => 'page', :previous_label => t("previous"), :next_label => t("next") %>
</div>
<% end %>
<br>

<%= link_to 'bac', account_settings_path %>